apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mars.fullname" . }}-config
  labels:
    {{- include "mars.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.spring.profiles.active | quote }}
  SPRING_DATASOURCE_URL: {{ printf "jdbc:postgresql://%s:%v/%s" .Values.externalDatabase.host (.Values.externalDatabase.port | int) .Values.externalDatabase.database | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.externalDatabase.username | quote }}
  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.externalKafka.bootstrapServers | quote }}
  SERVER_PORT: {{ .Values.service.targetPort | quote }}
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
