{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mars.fullname" . }}-secret
  labels:
    {{- include "mars.labels" . | nindent 4 }}
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.spring.datasource.password | b64enc | quote }}
{{- end }}
