apiVersion: v1
kind: Service
metadata:
  name: {{ include "mars.fullname" . }}
  labels:
    {{- include "mars.labels" . | nindent 4 }}
  {{- with .Values.kong.upstreamPolicy }}
  annotations:
    konghq.com/upstream-policy: {{ . | quote }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "mars.selectorLabels" . | nindent 4 }}
