apiVersion: v1
kind: Service
metadata:
  name: signoz-tailscale
  namespace: signoz
  annotations:
    tailscale.com/hostname: "signoz-lab"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/component: signoz
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/name: signoz
  ports:
  - name: http
    port: 80
    targetPort: 8080
