apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kong-dataplane
  namespace: kong
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: kong-phcfh
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
